name: stil_asist
description: "Weather-based style assistant for women"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  go_router: ^14.8.0
  flutter_riverpod: ^3.2.1
  dio: ^5.7.0
  intl: ^0.19.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  shared_preferences: ^2.5.2
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  equatable: ^2.0.7
  flutter_svg: ^2.0.17
  permission_handler: ^11.3.1
  connectivity_plus: ^6.1.3
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  uuid: ^4.5.2
  firebase_core: ^3.6.0
  cloud_functions: ^5.1.0
  firebase_auth: ^5.7.0
  google_sign_in: ^7.2.0
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  google_ml_kit: ^0.18.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  google_maps_flutter: ^2.6.0
  package_info_plus: ^8.1.2
  geoflutterfire_plus: ^0.0.4
  firebase_crashlytics: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
